apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: daft-lisp-test
spec:
  environments:
    - name: dev
      build:
        from: master
  components:
    - name: server
      src: .
      ports:
        - name: http
          port: 4242
      publicPort: http
      environmentConfig:
        - environment: dev
          monitoring: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
  dnsAppAlias:
    environment: dev
    component: server